# Generated by Django 3.0.8 on 2020-08-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('mainhead', models.CharField(default='', max_length=500)),
                ('cmainhead', models.CharField(default='', max_length=5000)),
                ('head', models.CharField(default='', max_length=500)),
                ('chead', models.CharField(default='', max_length=5000)),
                ('subhead', models.CharField(default='', max_length=500)),
                ('csubhead', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
